title: Python and C++ Samples
description: Python and C++ Samples
makrdown: kramdown
google_analytics: G-PP1WS30XD2
footer-links:
  github: devchait
  linkedin: https://www.linkedin.com/in/chaitanya-khire-7b35419a
permalink: /docs/blog/:year/:month/:day/:title
github_comments_repository: devchait.github.io
plugins: jekyll-sitemap



